name: compass
version: 0.0.1
author: Valor Zhong <valorzhong@gmail.com>
description: A 2D rendering engine that uses WebGL
homepage: http://valorzhong.blogspot.sg
documentation: http://valorzhong.blogspot.sg
dependencies:
  browser: any
  stats: any
  vector_math: 1.3.1
